"use client";

import { useId } from "react";

/**
 * Small accessible charts in inline SVG. Each chart is a <figure> with a caption; the drawing is hidden from
 * assistive tech and replaced by a real data table (visually hidden) so every value is available as text.
 * Colours come from the design tokens (CSS variables generated by Tailwind's @theme).
 */

export const SERIES_COLORS = ["var(--color-navy)", "var(--color-gold)", "var(--color-sage)", "var(--color-rose)"] as const;

export interface Datum { label: string; value: number }

function SrTable({ caption, head, rows }: { caption: string; head: string[]; rows: (string | number)[][] }) {
  return (
    <table className="sr-only">
      <caption>{caption}</caption>
      <thead><tr>{head.map((h) => <th key={h} scope="col">{h}</th>)}</tr></thead>
      <tbody>{rows.map((r, i) => <tr key={i}>{r.map((c, j) => (j === 0 ? <th key={j} scope="row">{c}</th> : <td key={j}>{c}</td>))}</tr>)}</tbody>
    </table>
  );
}

const W = 320;
const H = 190;
const TOP = 22;
const BOTTOM = 26;

/** Vertical bars, one per period. */
export function BarChart({ caption, data, formatValue, formatLabel, valueHeader, labelHeader }: {
  caption: string;
  data: Datum[];
  formatValue: (n: number) => string;
  formatLabel?: (n: number) => string;
  valueHeader: string;
  labelHeader: string;
}) {
  const max = Math.max(...data.map((d) => d.value), 1);
  const slot = W / data.length;
  const bw = Math.min(34, slot * 0.58);
  const plot = H - TOP - BOTTOM;
  return (
    <figure>
      <figcaption className="sr-only">{caption}</figcaption>
      <svg viewBox={`0 0 ${W} ${H}`} style={{ direction: "ltr" }} className="h-auto w-full" aria-hidden="true">
        <line x1="0" x2={W} y1={H - BOTTOM} y2={H - BOTTOM} stroke="var(--color-line)" />
        {data.map((d, i) => {
          const h = (d.value / max) * plot;
          const x = i * slot + (slot - bw) / 2;
          return (
            <g key={d.label}>
              <rect x={x} y={H - BOTTOM - h} width={bw} height={Math.max(h, d.value > 0 ? 2 : 0)} rx="5" fill="var(--color-navy)" opacity={i === data.length - 1 ? 1 : 0.82} />
              <text x={x + bw / 2} y={H - BOTTOM - h - 6} textAnchor="middle" fontSize="11" fontWeight="600" className="fill-oud">{(formatLabel ?? formatValue)(d.value)}</text>
              <text x={x + bw / 2} y={H - 8} textAnchor="middle" fontSize="11" className="fill-oud-soft">{d.label}</text>
            </g>
          );
        })}
      </svg>
      <SrTable caption={caption} head={[labelHeader, valueHeader]} rows={data.map((d) => [d.label, formatValue(d.value)])} />
    </figure>
  );
}

export interface Series { key: string; label: string }

/** Stacked bars (one per period) with a legend; every segment is also listed in the hidden table. */
export function StackedBarChart({ caption, series, rows, labelHeader, formatValue }: {
  caption: string;
  series: Series[];
  rows: { label: string; total: number; values: Record<string, number> }[];
  labelHeader: string;
  formatValue: (n: number) => string;
}) {
  const max = Math.max(...rows.map((r) => r.total), 1);
  const slot = W / rows.length;
  const bw = Math.min(34, slot * 0.58);
  const plot = H - TOP - BOTTOM;
  const patternId = useId();
  return (
    <figure>
      <figcaption className="sr-only">{caption}</figcaption>
      <svg viewBox={`0 0 ${W} ${H}`} style={{ direction: "ltr" }} className="h-auto w-full" aria-hidden="true">
        <defs>
          {/* Hatch on the second and fourth series so colour is never the only signal. */}
          <pattern id={`${patternId}-h`} width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
            <rect width="5" height="5" fill="var(--color-gold)" /><line x1="0" y1="0" x2="0" y2="5" stroke="var(--color-ivory)" strokeWidth="1.6" />
          </pattern>
          <pattern id={`${patternId}-r`} width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(-45)">
            <rect width="5" height="5" fill="var(--color-rose)" /><line x1="0" y1="0" x2="0" y2="5" stroke="var(--color-ivory)" strokeWidth="1.6" />
          </pattern>
        </defs>
        <line x1="0" x2={W} y1={H - BOTTOM} y2={H - BOTTOM} stroke="var(--color-line)" />
        {rows.map((r, i) => {
          const x = i * slot + (slot - bw) / 2;
          let y = H - BOTTOM;
          return (
            <g key={r.label}>
              {series.map((s, si) => {
                const v = r.values[s.key] ?? 0;
                const h = (v / max) * plot;
                y -= h;
                return v > 0 ? <rect key={s.key} x={x} y={y} width={bw} height={h} fill={fillFor(si, patternId)} stroke="var(--color-ivory)" strokeWidth="0.8" /> : null;
              })}
              <text x={x + bw / 2} y={H - BOTTOM - (r.total / max) * plot - 6} textAnchor="middle" fontSize="11" fontWeight="600" className="fill-oud">{r.total > 0 ? formatValue(r.total) : ""}</text>
              <text x={x + bw / 2} y={H - 8} textAnchor="middle" fontSize="11" className="fill-oud-soft">{r.label}</text>
            </g>
          );
        })}
      </svg>
      <ul className="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-xs text-oud-soft">
        {series.map((s, si) => (
          <li key={s.key} className="inline-flex items-center gap-1.5">
            <svg width="14" height="14" aria-hidden="true"><rect width="14" height="14" rx="3" fill={fillFor(si, patternId)} /></svg>
            {s.label}
          </li>
        ))}
      </ul>
      <SrTable caption={caption} head={[labelHeader, ...series.map((s) => s.label)]} rows={rows.map((r) => [r.label, ...series.map((s) => formatValue(r.values[s.key] ?? 0))])} />
    </figure>
  );
}

function fillFor(i: number, id: string) {
  if (i === 1) return `url(#${id}-h)`;
  if (i === 3) return `url(#${id}-r)`;
  return SERIES_COLORS[i];
}

/** Horizontal bars as a list: label, bar and value are all real text. */
export function HBars({ data, formatValue, tone = "navy" }: { data: Datum[]; formatValue: (n: number) => string; tone?: "navy" | "gold" | "sage" }) {
  const max = Math.max(...data.map((d) => d.value), 1);
  const bar = { navy: "bg-navy", gold: "bg-gold", sage: "bg-sage" }[tone];
  return (
    <ul className="space-y-3">
      {data.map((d) => (
        <li key={d.label}>
          <div className="flex items-baseline justify-between gap-3 text-sm">
            <span className="text-oud">{d.label}</span>
            <span className="font-semibold tabular-nums text-navy">{formatValue(d.value)}</span>
          </div>
          <div className="mt-1 h-2.5 overflow-hidden rounded-full bg-sand" aria-hidden="true">
            <div className={`h-full rounded-full ${bar}`} style={{ width: `${(d.value / max) * 100}%` }} />
          </div>
        </li>
      ))}
    </ul>
  );
}
