import { CALLIGRAPHY } from "@/lib/calligraphy";

/**
 * Arabic "حكايتي" as live calligraphy. The letterforms are the real Amiri outlines (generated by
 * scripts/build-calligraphy.mjs); each glyph sits behind an SVG <mask> whose pen strokes are drawn
 * on by CSS (see `.hk-pen` / `.hk-dot` in globals.css). Pure SVG + CSS: no video, no JS.
 */
export function Calligraphy({ className = "" }: { className?: string }) {
  const { viewBox, glyphs } = CALLIGRAPHY;
  return (
    <svg viewBox={viewBox} className={className} role="img" aria-label="حكايتي" fill="currentColor">
      <defs>
        {glyphs.map((g, i) => (
          <mask key={i} id={`hk-mask-${i}`} maskUnits="userSpaceOnUse" x="-200" y="-1000" width="3000" height="1800">
            {g.strokes.map((s, j) => (
              <path
                key={j}
                d={s.d}
                pathLength={1}
                fill="none"
                stroke="#fff"
                strokeWidth={s.w}
                strokeLinecap="round"
                strokeLinejoin="round"
                className="hk-pen"
                style={{ "--at": `${s.at}s`, "--dur": `${s.dur}s` } as React.CSSProperties}
              />
            ))}
            {g.dots.map((c, j) => (
              <circle
                key={j}
                cx={c.cx}
                cy={c.cy}
                r={c.r}
                fill="#fff"
                className="hk-dot"
                style={{ "--at": `${c.at}s` } as React.CSSProperties}
              />
            ))}
          </mask>
        ))}
      </defs>
      {glyphs.map((g, i) => (
        <g key={i} mask={`url(#hk-mask-${i})`}>
          <path d={g.d} transform={g.transform} />
        </g>
      ))}
    </svg>
  );
}

/**
 * The hero lockup. HIKAYATI stays perfectly still; the Arabic word is written beneath and across
 * its lower right edge, tilted like a signature, in a quieter olive so the two feel layered.
 */
export function BrandMark() {
  return (
    <div className="relative mx-auto w-fit pb-[17vw] sm:pb-[11vw] lg:pb-[8rem]" dir="ltr">
      <h1
        className="font-light leading-none tracking-[0.1em] text-ink sm:tracking-[0.16em]"
        style={{ fontFamily: "var(--font-cormorant), serif", fontSize: "clamp(2.4rem, 12.5vw, 9.5rem)" }}
        aria-label="Hikayati — حكايتي"
      >
        HIKAYATI
      </h1>
      {/* hairline that the Arabic crosses */}
      <span aria-hidden className="absolute inset-x-0 top-[96%] hairline" />
      <Calligraphy className="pointer-events-none absolute -bottom-[4%] end-[2%] w-[41%] -rotate-[5deg] text-olive/90 mix-blend-multiply" />
    </div>
  );
}
